# Generated by Django 2.2.3 on 2020-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='category',
            field=models.CharField(default='Gaming', max_length=100),
        ),
    ]
