# Generated by Django 2.2.3 on 2020-01-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='choice',
            field=models.CharField(default='Experience', max_length=100),
        ),
    ]
